language: cpp 
dist: trusty 
sudo: required 
env: 
 matrix: 
  - PACKAGE='AABB_tree Advancing_front_surface_reconstruction Algebraic_foundations ' 
  - PACKAGE='Algebraic_kernel_d Algebraic_kernel_for_circles Algebraic_kernel_for_spheres ' 
  - PACKAGE='Alpha_shapes_2 Alpha_shapes_3 Apollonius_graph_2 ' 
  - PACKAGE='Arithmetic_kernel Arrangement_on_surface_2 Barycentric_coordinates_2 ' 
  - PACKAGE='BGL Boolean_set_operations_2 Bounding_volumes ' 
  - PACKAGE='Box_intersection_d CGAL_ImageIO CGAL_ipelets ' 
  - PACKAGE='Circular_kernel_2 Circular_kernel_3 Circulator ' 
  - PACKAGE='Combinatorial_map Cone_spanners_2 Convex_decomposition_3 ' 
  - PACKAGE='Convex_hull_2 Convex_hull_3 Convex_hull_d ' 
  - PACKAGE='Distance_2 Distance_3 Envelope_2 ' 
  - PACKAGE='Envelope_3 Filtered_kernel Generalized_map ' 
  - PACKAGE='Generator Geomview GraphicsView ' 
  - PACKAGE='HalfedgeDS Hash_map Inscribed_areas ' 
  - PACKAGE='Installation Interpolation Intersections_2 ' 
  - PACKAGE='Intersections_3 Interval_skip_list Interval_support ' 
  - PACKAGE='Inventor Jet_fitting_3 Kernel_23 ' 
  - PACKAGE='Kernel_d Kinetic_data_structures Kinetic_framework ' 
  - PACKAGE='Linear_cell_complex Matrix_search Mesh_2 ' 
  - PACKAGE='Mesh_3 Minkowski_sum_2 Minkowski_sum_3 ' 
  - PACKAGE='Modifier Modular_arithmetic Nef_2 ' 
  - PACKAGE='Nef_3 Nef_S2 NewKernel_d ' 
  - PACKAGE='Number_types Operations_on_polyhedra Optimal_transportation_reconstruction_2 ' 
  - PACKAGE='Partition_2 Periodic_2_triangulation_2 Periodic_3_triangulation_3 ' 
  - PACKAGE='Point_set_2 Point_set_3 Point_set_processing_3 ' 
  - PACKAGE='Point_set_shape_detection_3 Poisson_surface_reconstruction_3 Polygon ' 
  - PACKAGE='Polygon_mesh_processing Polyhedron Polyhedron_IO ' 
  - PACKAGE='Polyline_simplification_2 Polynomial Polytope_distance_d ' 
  - PACKAGE='Principal_component_analysis Profiling_tools QP_solver ' 
  - PACKAGE='Random_numbers Ridges_3 Scale_space_reconstruction_3 ' 
  - PACKAGE='Segment_Delaunay_graph_2 Segment_Delaunay_graph_Linf_2 Skin_surface_3 ' 
  - PACKAGE='Snap_rounding_2 Solver_interface Spatial_searching ' 
  - PACKAGE='Spatial_sorting STL_Extension Straight_skeleton_2 ' 
  - PACKAGE='Stream_lines_2 Stream_support Subdivision_method_3 ' 
  - PACKAGE='Surface_mesh Surface_mesh_deformation Surface_mesher ' 
  - PACKAGE='Surface_mesh_parameterization Surface_mesh_segmentation Surface_mesh_shortest_path ' 
  - PACKAGE='Surface_mesh_simplification Surface_mesh_skeletonization Sweep_line_2 ' 
  - PACKAGE='TDS_2 TDS_3 Three ' 
  - PACKAGE='Triangulation Triangulation_2 Triangulation_3 ' 
  - PACKAGE='Union_find Visibility_2 Voronoi_diagram_2 ' 
  - PACKAGE='CHECK' 
install: 
before_script: 
- mkdir -p build 
- cd build 
- cmake -DCGAL_HEADER_ONLY=ON -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG .. 
- make 
- cd .. 
script: 
- cd ./.travis
- bash -x -e ./build_package.sh $PACKAGE
compiler: 
  - clang 
  - gcc 
addons: 
  apt: 
    packages: 
      - cmake 
      - libboost1.55-dev 
      - libboost-system1.55-dev 
      - libboost-program-options1.55-dev 
      - libboost-thread1.55-dev 
      - libgmp-dev 
      - libmpfr-dev 
      - zlib1g-dev 
      - libeigen3-dev # too old 
      # Not allowed (yet) 
      # - geomview 
      # - libglew1.5-dev 
      # - libipe-dev 
      # - libmpfi-dev 
      # Not found 
      # - libqglviewer-dev 
      # - qtbase5-dev 
      # - qtscript5-dev 
      # - libqt5svg5-dev 
      # - qttools5-dev 
      # - qttools5-dev-tools 
    sources: 
      - kalakris-cmake 
      - boost-latest 
